/**
 * Development Progress Dashboard
 *
 * Comprehensive bird's-eye view of Wyshbone development progress across all 4 repos.
 * Shows current state, blockers, phase progress, and the path to autonomous operation.
 */

import { useState, useEffect } from 'react';
import { RefreshCw, AlertTriangle, CheckCircle2, Clock, Loader2, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { getDevProgressData, DevProgressData } from '@/services/devProgressService';
import { ArchitectureHealth } from '@/components/dev-dashboard/ArchitectureHealth';
import { PhaseProgress } from '@/components/dev-dashboard/PhaseProgress';
import { AutonomyGap } from '@/components/dev-dashboard/AutonomyGap';
import { ComponentStatus } from '@/components/dev-dashboard/ComponentStatus';
import { BlockersDashboard } from '@/components/dev-dashboard/BlockersDashboard';
import { ToolStatus } from '@/components/dev-dashboard/ToolStatus';
import { DevelopmentVelocity } from '@/components/dev-dashboard/DevelopmentVelocity';
import { GapAnalysis } from '@/components/dev-dashboard/GapAnalysis';
import { QuickActions } from '@/components/dev-dashboard/QuickActions';

export default function DevProgressPage() {
  const [data, setData] = useState<DevProgressData | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  const loadData = async (forceRefresh: boolean = false) => {
    if (forceRefresh) {
      setRefreshing(true);
    } else {
      setLoading(true);
    }

    try {
      const progressData = await getDevProgressData(forceRefresh);
      setData(progressData);
      setLastUpdated(new Date(progressData.timestamp));
    } catch (error) {
      console.error('Failed to load dev progress data:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadData();

    // Auto-refresh every 30 seconds
    const pollInterval = setInterval(() => {
      loadData(true);
    }, 30000);

    return () => clearInterval(pollInterval);
  }, []);

  const handleRefresh = () => {
    loadData(true);
  };

  const handleDownloadReport = () => {
    if (!data) return;
    
    const report = `# Wyshbone Development Progress Report
Generated: ${new Date().toLocaleString()}

## Executive Summary
- **Current Phase:** ${data.overview.currentPhase}
- **Overall Completion:** ${data.overview.overallCompletion}%
- **Critical Blockers:** ${data.overview.criticalBlockersCount}
- **TODO Comments:** ${data.overview.todoCount}

## Autonomy Gap
- **Current State:** ${data.autonomyGap.current}
- **Target State:** ${data.autonomyGap.target}
- **Gap Remaining:** ${data.autonomyGap.gapPercentage}%
- **Missing Features:**
${data.autonomyGap.missingFeatures.map(f => `  - ${f}`).join('\n')}

## Phase Progress
${data.phases.map(phase => `
### ${phase.name}
- **Status:** ${phase.status}
- **Progress:** ${phase.completion}%
- **Duration:** ${phase.duration}
- **Tasks Completed:** ${phase.tasks.filter(t => t.status === 'completed').length}/${phase.tasks.length}
${phase.tasks.map(t => `  - [${t.status === 'completed' ? 'x' : ' '}] ${t.title} (${t.priority})`).join('\n')}
`).join('\n')}

## Component Status
${data.components.map(c => `- **${c.name}:** ${c.status}${(c.issues && c.issues.length > 0) ? ` (${c.issues.length} issues)` : ''}`).join('\n')}

## Blockers (${data.blockers.length} total)
${data.blockers.map(b => `- [${b.severity.toUpperCase()}] ${b.title}
  ${b.location ? `Location: ${b.location}` : ''}
  ${b.description}`).join('\n\n')}

## Repository Health
${data.repos.map(r => `- **${r.displayName}:** ${r.health} (${r.completion}% complete)`).join('\n')}

## Tools Status
${data.tools.map(t => `- **${t.name}:** ${t.status} - ${t.description}`).join('\n')}

## Development Velocity

### Recent Activity
${data.developmentVelocity.recentActivity.map(a => `- ${a}`).join('\n')}

### Active Areas
${data.developmentVelocity.activeAreas.map(a => `- ${a}`).join('\n')}

### Stale Areas (Need Attention)
${data.developmentVelocity.staleAreas.map(a => `- ${a}`).join('\n')}

### TODO Hotspots
${data.developmentVelocity.todosByFile.map(f => `- ${f.file}: ${f.count} TODOs`).join('\n')}

---
*Report generated by Wyshbone Dev Progress Dashboard*
`;
    
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wyshbone-progress-report-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[600px]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="h-12 w-12 animate-spin text-primary" />
          <p className="text-muted-foreground">Analyzing codebase...</p>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="flex items-center justify-center h-full min-h-[600px]">
        <div className="text-center">
          <AlertTriangle className="h-12 w-12 text-destructive mx-auto mb-4" />
          <p className="text-muted-foreground">Failed to load development progress data</p>
          <Button onClick={() => loadData(true)} className="mt-4">
            Retry
          </Button>
        </div>
      </div>
    );
  }

  const criticalBlockers = data.blockers.filter((b) => b.severity === 'critical');
  const highBlockers = data.blockers.filter((b) => b.severity === 'high');

  return (
    <div className="h-full overflow-y-auto bg-background">
      <div className="container mx-auto p-4 sm:p-6 lg:p-8 max-w-[1600px]">
        {/* Header */}
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">
                Development Progress Dashboard
              </h1>
              <p className="text-muted-foreground text-base sm:text-lg">
                Bird's-eye view of Wyshbone's journey to autonomous AI agent system
              </p>
            </div>
            <div className="flex items-center gap-3">
              <div className="text-sm text-muted-foreground">
                {lastUpdated && (
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4" />
                    <span>
                      Updated {lastUpdated.toLocaleTimeString()}
                    </span>
                  </div>
                )}
              </div>
              <Button
                onClick={handleDownloadReport}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <Download className="h-4 w-4" />
                Download Report
              </Button>
              <Button
                onClick={handleRefresh}
                disabled={refreshing}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} />
                Refresh
              </Button>
            </div>
          </div>

          {/* Overview Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            {/* Current Phase */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Current Phase
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.overview.currentPhase}</div>
                <p className="text-xs text-muted-foreground mt-1">In Progress</p>
              </CardContent>
            </Card>

            {/* Overall Completion */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Overall Completion
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.overview.overallCompletion}%</div>
                <div className="w-full bg-muted rounded-full h-2 mt-2">
                  <div
                    className="bg-primary h-2 rounded-full transition-all"
                    style={{ width: `${data.overview.overallCompletion}%` }}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Critical Blockers */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Critical Blockers
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2">
                  {criticalBlockers.length > 0 ? (
                    <>
                      <AlertTriangle className="h-6 w-6 text-destructive" />
                      <span className="text-2xl font-bold text-destructive">
                        {criticalBlockers.length}
                      </span>
                    </>
                  ) : (
                    <>
                      <CheckCircle2 className="h-6 w-6 text-green-500" />
                      <span className="text-2xl font-bold text-green-500">0</span>
                    </>
                  )}
                </div>
                {highBlockers.length > 0 && (
                  <p className="text-xs text-muted-foreground mt-1">
                    + {highBlockers.length} high priority
                  </p>
                )}
              </CardContent>
            </Card>

            {/* TODO Count */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  TODO Comments
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.overview.todoCount}</div>
                <p className="text-xs text-muted-foreground mt-1">Across 53 files</p>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Main Content Tabs */}
        <Tabs defaultValue="phases" className="space-y-6">
          <TabsList className="grid w-full grid-cols-2 sm:grid-cols-3 lg:grid-cols-6">
            <TabsTrigger value="phases" className="font-semibold">🚀 Phases</TabsTrigger>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="components">Components</TabsTrigger>
            <TabsTrigger value="blockers">Blockers</TabsTrigger>
            <TabsTrigger value="tools">Tools</TabsTrigger>
            <TabsTrigger value="velocity">Velocity</TabsTrigger>
          </TabsList>

          {/* Overview Tab */}
          <TabsContent value="overview" className="space-y-6">
            {/* Architecture Health */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">4-Repo Architecture Health</h2>
              <ArchitectureHealth repos={data.repos} />
            </section>

            {/* Autonomy Gap */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">The Path to Autonomy</h2>
              <AutonomyGap gap={data.autonomyGap} />
            </section>

            {/* Gap Analysis */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">What We Have vs What We Need</h2>
              <GapAnalysis phases={data.phases} components={data.components} />
            </section>

            {/* Quick Actions */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">Quick Actions</h2>
              <QuickActions />
            </section>
          </TabsContent>

          {/* Phases Tab */}
          <TabsContent value="phases">
            <PhaseProgress phases={data.phases} />
          </TabsContent>

          {/* Components Tab */}
          <TabsContent value="components">
            <ComponentStatus components={data.components} />
          </TabsContent>

          {/* Blockers Tab */}
          <TabsContent value="blockers">
            <BlockersDashboard blockers={data.blockers} />
          </TabsContent>

          {/* Tools Tab */}
          <TabsContent value="tools">
            <ToolStatus tools={data.tools} />
          </TabsContent>

          {/* Velocity Tab */}
          <TabsContent value="velocity">
            <DevelopmentVelocity velocity={data.developmentVelocity} />
          </TabsContent>
        </Tabs>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t text-center text-sm text-muted-foreground">
          <p>
            This dashboard is self-updating and scans the codebase to provide real-time insights.
          </p>
          <p className="mt-1">
            Last generated: {lastUpdated?.toLocaleString()} • Data cached for 5 minutes
          </p>
        </div>
      </div>
    </div>
  );
}
