/**
 * Sample brewery product data
 * Realistic beer products for UK breweries
 */

export const breweryProducts = [
  {
    name: "Sussex Best Bitter",
    style: "Bitter",
    abv: 4.2,
    category: "Cask Ale",
    container: "9g Cask (Firkin)",
    unitPrice: 72.50,
    status: "active" as const,
    description: "Traditional Sussex bitter with a balanced malty backbone",
  },
  {
    name: "Harvest Pale",
    style: "Pale Ale",
    abv: 4.8,
    category: "Keg Beer",
    container: "30L KeyKeg",
    unitPrice: 95.00,
    status: "active" as const,
    description: "Citrus and tropical hop character, unfiltered",
  },
  {
    name: "Porter",
    style: "Porter",
    abv: 5.0,
    category: "Cask Ale",
    container: "9g Cask (Firkin)",
    unitPrice: 75.00,
    status: "active" as const,
    description: "Rich chocolate and coffee notes, smooth finish",
  },
  {
    name: "Session IPA",
    style: "IPA",
    abv: 3.8,
    category: "Keg Beer",
    container: "20L Keg",
    unitPrice: 65.00,
    status: "active" as const,
    description: "Light and hoppy, perfect for all-day drinking",
  },
  {
    name: "Golden Ale",
    style: "Golden Ale",
    abv: 4.5,
    category: "Cask Ale",
    container: "9g Cask (Firkin)",
    unitPrice: 70.00,
    status: "active" as const,
    description: "Refreshing golden ale with floral hop notes",
  },
  {
    name: "Stout",
    style: "Stout",
    abv: 5.5,
    category: "Keg Beer",
    container: "30L KeyKeg",
    unitPrice: 98.00,
    status: "active" as const,
    description: "Creamy nitro stout with roasted malt complexity",
  },
  {
    name: "American Pale Ale",
    style: "APA",
    abv: 5.2,
    category: "Keg Beer",
    container: "20L Keg",
    unitPrice: 72.00,
    status: "active" as const,
    description: "Bold American hops with citrus and pine",
  },
  {
    name: "Wheat Beer",
    style: "Wheat Beer",
    abv: 4.3,
    category: "Keg Beer",
    container: "30L KeyKeg",
    unitPrice: 92.00,
    status: "active" as const,
    description: "Bavarian-style wheat beer, banana and clove esters",
  },
];
