import type { Lead } from "./types";

/**
 * Mock leads data for UI-6
 * This will be replaced with real API data in a future task.
 */
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    businessName: "The Rusty Anchor Pub",
    location: "Leeds, UK",
    source: "google",
    status: "new",
  },
  {
    id: "lead-002",
    businessName: "Brightside Dental Clinic",
    location: "Manchester, UK",
    source: "database",
    status: "contacted",
  },
  {
    id: "lead-003",
    businessName: "Bean & Brew Coffee House",
    location: "Bristol, UK",
    source: "google",
    status: "qualified",
  },
  {
    id: "lead-004",
    businessName: "Green Valley Veterinary",
    location: "Birmingham, UK",
    source: "manual",
    status: "new",
  },
  {
    id: "lead-005",
    businessName: "Urban Fitness Studio",
    location: "London, UK",
    source: "google",
    status: "do_not_contact",
  },
  {
    id: "lead-006",
    businessName: "Cornerstone Bakery",
    location: "Edinburgh, UK",
    source: "database",
    status: "qualified",
  },
  {
    id: "lead-007",
    businessName: "Summit Accounting Services",
    location: "Glasgow, UK",
    source: "google",
    status: "new",
  },
  {
    id: "lead-008",
    businessName: "Coastal Hair Salon",
    location: "Brighton, UK",
    source: "manual",
    status: "contacted",
  },
  {
    id: "lead-009",
    businessName: "Northside Auto Repairs",
    location: "Newcastle, UK",
    source: "database",
    status: "new",
  },
  {
    id: "lead-010",
    businessName: "Harmony Yoga Studio",
    location: "Oxford, UK",
    source: "google",
    status: "qualified",
  },
  {
    id: "lead-011",
    businessName: "Riverside Plumbing Co",
    location: "Cambridge, UK",
    source: "manual",
    status: "new",
  },
  {
    id: "lead-012",
    businessName: "Metro Legal Partners",
    location: "Liverpool, UK",
    source: "database",
    status: "contacted",
  },
  {
    id: "lead-013",
    businessName: "Golden Gate Chinese",
    location: "Sheffield, UK",
    source: "google",
    status: "new",
  },
  {
    id: "lead-014",
    businessName: "Sunrise Childcare Centre",
    location: "Nottingham, UK",
    source: "manual",
    status: "do_not_contact",
  },
  {
    id: "lead-015",
    businessName: "Peak Performance Physio",
    location: "Cardiff, UK",
    source: "database",
    status: "qualified",
  },
  {
    id: "lead-016",
    businessName: "Craft & Draft Brewery",
    location: "York, UK",
    source: "google",
    status: "new",
  },
  {
    id: "lead-017",
    businessName: "Bluebell Florist",
    location: "Bath, UK",
    source: "manual",
    status: "contacted",
  },
  {
    id: "lead-018",
    businessName: "TechStart IT Solutions",
    location: "Reading, UK",
    source: "database",
    status: "new",
  },
  {
    id: "lead-019",
    businessName: "Woodland Pet Supplies",
    location: "Southampton, UK",
    source: "google",
    status: "qualified",
  },
  {
    id: "lead-020",
    businessName: "Evergreen Landscaping",
    location: "Leicester, UK",
    source: "manual",
    status: "new",
  },
  {
    id: "lead-021",
    businessName: "Central Opticians",
    location: "Coventry, UK",
    source: "database",
    status: "contacted",
  },
  {
    id: "lead-022",
    businessName: "Moonlight Thai Kitchen",
    location: "Derby, UK",
    source: "google",
    status: "new",
  },
  {
    id: "lead-023",
    businessName: "Starlight Dance Academy",
    location: "Plymouth, UK",
    source: "manual",
    status: "do_not_contact",
  },
  {
    id: "lead-024",
    businessName: "Harbour Fish & Chips",
    location: "Portsmouth, UK",
    source: "google",
    status: "qualified",
  },
  {
    id: "lead-025",
    businessName: "Phoenix Insurance Brokers",
    location: "Belfast, UK",
    source: "database",
    status: "new",
  },
];
