import type { Lead } from "./types";

/**
 * Mock leads data for UI-6, updated for UI-14 with brewery-specific fields.
 * This will be replaced with real API data in a future task.
 * 
 * UI-14: Added breweryMetadata to pub-type leads to demonstrate
 * the brewery vertical field display functionality.
 */
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    businessName: "The Rusty Anchor",
    location: "Leeds, UK",
    source: "google",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 4,
      kegLines: 8,
      rotationStyle: "Rotating guests",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: true,
      venueNotes: "Traditional freehouse with strong local following. Landlord interested in local breweries.",
    },
  },
  {
    id: "lead-002",
    businessName: "The Crown & Anchor",
    location: "Manchester, UK",
    source: "database",
    status: "contacted",
    breweryMetadata: {
      pubType: "tied",
      beerRangeSummary: "2 cask, 4 keg (tied to Marston's)",
      rotationStyle: "Limited rotation",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
    },
  },
  {
    id: "lead-003",
    businessName: "The Hop & Vine",
    location: "Bristol, UK",
    source: "google",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 6,
      kegLines: 12,
      rotationStyle: "Always rotating - craft focused",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: true,
      venueNotes: "Excellent craft beer bar. Very open to new breweries. Owner is a CAMRA member.",
    },
  },
  {
    id: "lead-004",
    businessName: "The King's Arms",
    location: "Birmingham, UK",
    source: "manual",
    status: "new",
    breweryMetadata: {
      pubType: "pubco",
      beerRangeSummary: "3 cask, 6 keg",
      rotationStyle: "Core range only",
      caskBias: "keg-led",
      servesFood: false,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-005",
    businessName: "The Red Lion",
    location: "London, UK",
    source: "google",
    status: "do_not_contact",
    breweryMetadata: {
      pubType: "group",
      beerRangeSummary: "Corporate beer list only",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
      venueNotes: "Part of large chain. No decision-making power on beer selection.",
    },
  },
  {
    id: "lead-006",
    businessName: "The Barrel House",
    location: "Edinburgh, UK",
    source: "database",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 8,
      kegLines: 6,
      rotationStyle: "Seasonal rotation",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: false,
      venueNotes: "Cask specialist. Very interested in session bitters and pale ales.",
    },
  },
  {
    id: "lead-007",
    businessName: "The White Hart",
    location: "Glasgow, UK",
    source: "google",
    status: "new",
    breweryMetadata: {
      pubType: "independent",
      caskLines: 3,
      kegLines: 10,
      rotationStyle: "Rotating guests",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-008",
    businessName: "The Wheatsheaf",
    location: "Brighton, UK",
    source: "manual",
    status: "contacted",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 5,
      kegLines: 8,
      rotationStyle: "Local breweries only",
      caskBias: "cask-led",
      servesFood: false,
      hasBeerGarden: true,
      venueNotes: "Strongly supports local breweries. Good fit for our distribution area.",
    },
  },
  {
    id: "lead-009",
    businessName: "The Black Swan",
    location: "Newcastle, UK",
    source: "database",
    status: "new",
    breweryMetadata: {
      pubType: "tied",
      beerRangeSummary: "2 cask (house beers), 4 keg",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
    },
  },
  {
    id: "lead-010",
    businessName: "The Old Mill",
    location: "Oxford, UK",
    source: "google",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 4,
      kegLines: 6,
      rotationStyle: "Mix of core and rotating",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: true,
      venueNotes: "Riverside pub with good food trade. Looking for premium craft options.",
    },
  },
  {
    id: "lead-011",
    businessName: "The Ploughman's Rest",
    location: "Cambridge, UK",
    source: "manual",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 6,
      kegLines: 4,
      rotationStyle: "Traditional ales focus",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-012",
    businessName: "The Shipwright's Arms",
    location: "Liverpool, UK",
    source: "database",
    status: "contacted",
    breweryMetadata: {
      pubType: "independent",
      caskLines: 3,
      kegLines: 8,
      rotationStyle: "Rotating guests",
      caskBias: "balanced",
      servesFood: false,
      hasBeerGarden: false,
    },
  },
  {
    id: "lead-013",
    businessName: "The Fox & Hounds",
    location: "Sheffield, UK",
    source: "google",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 5,
      kegLines: 7,
      rotationStyle: "Weekly rotation",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-014",
    businessName: "The Railway Tavern",
    location: "Nottingham, UK",
    source: "manual",
    status: "do_not_contact",
    breweryMetadata: {
      pubType: "pubco",
      beerRangeSummary: "Fixed beer list",
      caskBias: "keg-led",
      servesFood: false,
      hasBeerGarden: false,
      venueNotes: "Under pubco contract - cannot change beer suppliers.",
    },
  },
  {
    id: "lead-015",
    businessName: "The Craftsman",
    location: "Cardiff, UK",
    source: "database",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 4,
      kegLines: 16,
      rotationStyle: "Craft keg specialist",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
      venueNotes: "Modern craft beer bar. Looking for interesting keg beers and sours.",
    },
  },
  {
    id: "lead-016",
    businessName: "The Brewery Tap",
    location: "York, UK",
    source: "google",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 10,
      kegLines: 8,
      rotationStyle: "Always rotating",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: true,
      venueNotes: "Excellent cask beer destination. Very well connected in beer community.",
    },
  },
  {
    id: "lead-017",
    businessName: "The Market Tavern",
    location: "Bath, UK",
    source: "manual",
    status: "contacted",
    breweryMetadata: {
      pubType: "independent",
      caskLines: 3,
      kegLines: 5,
      rotationStyle: "Seasonal changes",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: false,
    },
  },
  {
    id: "lead-018",
    businessName: "The Bridge Inn",
    location: "Reading, UK",
    source: "database",
    status: "new",
    breweryMetadata: {
      pubType: "tied",
      beerRangeSummary: "2 cask, 6 keg (Greene King)",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-019",
    businessName: "The Taproom",
    location: "Southampton, UK",
    source: "google",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 6,
      kegLines: 14,
      rotationStyle: "Weekly rotation",
      caskBias: "balanced",
      servesFood: false,
      hasBeerGarden: true,
      venueNotes: "Popular taproom. Great social media presence. Would be good for tap takeovers.",
    },
  },
  {
    id: "lead-020",
    businessName: "The Village Inn",
    location: "Leicester, UK",
    source: "manual",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 4,
      kegLines: 4,
      rotationStyle: "Core range with occasional guests",
      caskBias: "cask-led",
      servesFood: true,
      hasBeerGarden: true,
    },
  },
  {
    id: "lead-021",
    businessName: "The Golden Fleece",
    location: "Coventry, UK",
    source: "database",
    status: "contacted",
    breweryMetadata: {
      pubType: "independent",
      caskLines: 3,
      kegLines: 6,
      rotationStyle: "Rotating guests",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: false,
    },
  },
  {
    id: "lead-022",
    businessName: "The Hop Garden",
    location: "Derby, UK",
    source: "google",
    status: "new",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 8,
      kegLines: 6,
      rotationStyle: "Cask specialist",
      caskBias: "cask-led",
      servesFood: false,
      hasBeerGarden: true,
      venueNotes: "CAMRA pub of the year nominee. Very cask-focused clientele.",
    },
  },
  {
    id: "lead-023",
    businessName: "The Cornerhouse",
    location: "Plymouth, UK",
    source: "manual",
    status: "do_not_contact",
    breweryMetadata: {
      pubType: "group",
      beerRangeSummary: "Fixed corporate list",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
      venueNotes: "Chain pub - no flexibility on beer selection.",
    },
  },
  {
    id: "lead-024",
    businessName: "The Harbour Arms",
    location: "Portsmouth, UK",
    source: "google",
    status: "qualified",
    breweryMetadata: {
      pubType: "freehouse",
      caskLines: 5,
      kegLines: 10,
      rotationStyle: "Mix of local and national",
      caskBias: "balanced",
      servesFood: true,
      hasBeerGarden: true,
      venueNotes: "Waterfront pub with good tourist trade. Interested in session beers.",
    },
  },
  {
    id: "lead-025",
    businessName: "The Merchant's House",
    location: "Belfast, UK",
    source: "database",
    status: "new",
    breweryMetadata: {
      pubType: "independent",
      caskLines: 2,
      kegLines: 12,
      rotationStyle: "Craft keg focus",
      caskBias: "keg-led",
      servesFood: true,
      hasBeerGarden: false,
    },
  },
];
